### ISSUE TITLE
move Ex3 to own repo

### ISSUE THREAD

**Issue by spencermathews** [ertran/ex1#2]
and please call it ex3, not Ex3

**Comment by ertran** [comment]
I went in and adjusted some things.  I seem to have files inside the ex3
and ex4 repos, but my ex1 got lost somehow and it won't seem to let me
update it.
I'm not sure if its safe to delete that one.  Im also not too sure how
it'll all link together without placing ex3-4 in the ex1 folder.

Hopefully there will be time in class today.

-Eric

**Comment by spencermathews** [comment]
Closing to clean up open issues.
